namespace NeoAdmin.Blazor.SeedData;

/// <summary>页面内 Tabs 子标签，供全局搜索索引。</summary>
public static class PageSearchTabSeedData
{
    public sealed record Entry(string PagePath, string TabValue, string TabLabel);

    public static IReadOnlyList<Entry> Entries { get; } =
    [
        new("/neo-demo/comp/dict-param", "dict", "字典演示"),
        new("/neo-demo/comp/dict-param", "param", "参数配置"),
        new("/neo-demo/comp/permission-guide", "overview", "权限-模型概览"),
        new("/neo-demo/comp/permission-guide", "page-role", "权限-页面与角色"),
        new("/neo-demo/comp/permission-guide", "route-menu", "权限-路由与菜单"),
        new("/neo-demo/comp/permission-guide", "button-crud", "权限-按钮与表格"),
        new("/neo-demo/comp/permission-guide", "nova-api", "权限-NovaButton与API"),
        new("/neo-demo/comp/permission-guide", "practice", "权限-本地验证"),
        new("/neo-demo/comp/select-components", "select-dict", "NeoSelectDict"),
        new("/neo-demo/comp/select-components", "select-enum", "NeoSelectEnum"),
        new("/neo-demo/comp/select-components", "select-entity", "NeoSelectEntity"),
        new("/neo-demo/comp/select-components", "input-table", "NeoInputTable"),
        new("/neo-demo/comp/select-components", "select-table", "NeoSelectTable"),
        new("/neo-demo/comp/select-components", "input-tags", "NeoInputTags"),
        new("/neo-demo/comp/select-components", "alloc-table", "NeoAllocTable"),
        new("/neo-demo/ui/advanced-complex", "dynamic-form", "Dynamic Form"),
        new("/neo-demo/ui/advanced-complex", "file-upload", "File Upload"),
        new("/neo-demo/ui/advanced-complex", "filter-builder", "Filter Builder"),
        new("/neo-demo/ui/advanced-complex", "markdown-editor", "Markdown Editor"),
        new("/neo-demo/ui/advanced-complex", "rich-text-editor", "Rich Text Editor"),
        new("/neo-demo/ui/advanced-complex", "range-slider", "Range Slider"),
        new("/neo-demo/ui/advanced-datetime", "calendar", "Calendar"),
        new("/neo-demo/ui/advanced-datetime", "date-input", "Date Input"),
        new("/neo-demo/ui/advanced-datetime", "date-picker", "Date Picker"),
        new("/neo-demo/ui/advanced-datetime", "date-range-picker", "Date Range Picker"),
        new("/neo-demo/ui/advanced-datetime", "time-input", "Time Input"),
        new("/neo-demo/ui/advanced-datetime", "time-picker", "Time Picker"),
        new("/neo-demo/ui/advanced-inputs", "combobox", "Combobox"),
        new("/neo-demo/ui/advanced-inputs", "multi-select", "Multi Select"),
        new("/neo-demo/ui/advanced-inputs", "tag-input", "Tag Input"),
        new("/neo-demo/ui/advanced-inputs", "color-picker", "Color Picker"),
        new("/neo-demo/ui/advanced-inputs", "currency-input", "Currency Input"),
        new("/neo-demo/ui/advanced-inputs", "masked-input", "Masked Input"),
        new("/neo-demo/ui/advanced-inputs", "input-otp", "Input OTP"),
        new("/neo-demo/ui/advanced-inputs", "input-group", "Input Group"),
        new("/neo-demo/comp/animation", "carousel", "Carousel"),
        new("/neo-demo/comp/animation", "motion", "Motion"),
        new("/neo-demo/comp/animation", "page-transition", "Page Transition"),
        new("/neo-demo/comp/animation", "screen-transition", "Screen Transition"),
        new("/neo-demo/comp/animation", "selection-indicator", "Selection Indicator"),
        new("/neo-demo/ui/chart", "overview", "入门示例"),
        new("/neo-demo/ui/chart", "area", "Area"),
        new("/neo-demo/ui/chart", "bar", "Bar"),
        new("/neo-demo/ui/chart", "line", "Line"),
        new("/neo-demo/ui/chart", "pie", "Pie"),
        new("/neo-demo/ui/chart", "scatter", "Scatter"),
        new("/neo-demo/ui/chart", "radar", "Radar"),
        new("/neo-demo/ui/chart", "radial-bar", "Radial Bar"),
        new("/neo-demo/ui/chart", "composed", "Composed"),
        new("/neo-demo/ui/chart", "candlestick", "Candlestick"),
        new("/neo-demo/ui/chart", "funnel", "Funnel"),
        new("/neo-demo/ui/chart", "gauge", "Gauge"),
        new("/neo-demo/ui/chart", "heatmap", "Heatmap"),
        new("/neo-demo/ui/data-display", "data-table", "Data Table"),
        new("/neo-demo/ui/data-display", "data-grid", "Data Grid"),
        new("/neo-demo/ui/data-display", "data-view", "Data View"),
        new("/neo-demo/ui/data-display", "tree-view", "Tree View"),
        new("/neo-demo/ui/data-display", "timeline", "Timeline"),
        new("/neo-demo/ui/display-basics", "aspect-ratio", "Aspect Ratio"),
        new("/neo-demo/ui/display-basics", "avatar", "Avatar"),
        new("/neo-demo/ui/display-basics", "badge", "Badge"),
        new("/neo-demo/ui/display-basics", "card", "Card"),
        new("/neo-demo/ui/display-basics", "typography", "Typography"),
        new("/neo-demo/ui/display-states", "empty", "Empty"),
        new("/neo-demo/ui/display-states", "skeleton", "Skeleton"),
        new("/neo-demo/ui/display-states", "item", "Item"),
        new("/neo-demo/ui/display-states", "kbd", "Kbd"),
        new("/neo-demo/ui/display-states", "scroll-area", "Scroll Area"),
        new("/neo-demo/ui/feedback", "alert", "Alert"),
        new("/neo-demo/ui/feedback", "progress", "Progress"),
        new("/neo-demo/ui/feedback", "spinner", "Spinner"),
        new("/neo-demo/ui/feedback", "toast", "Toast"),
        new("/neo-demo/ui/form-controls", "checkbox", "Checkbox"),
        new("/neo-demo/ui/form-controls", "native-select", "Native Select"),
        new("/neo-demo/ui/form-controls", "radio-group", "Radio Group"),
        new("/neo-demo/ui/form-controls", "select", "Select"),
        new("/neo-demo/ui/form-controls", "slider", "Slider"),
        new("/neo-demo/ui/form-controls", "switch", "Switch"),
        new("/neo-demo/ui/form-controls", "rating", "Rating"),
        new("/neo-demo/ui/form-controls", "toggle", "Toggle"),
        new("/neo-demo/ui/form-controls", "toggle-group", "Toggle Group"),
        new("/neo-demo/ui/form-inputs", "field", "Field"),
        new("/neo-demo/ui/form-inputs", "input", "Input"),
        new("/neo-demo/ui/form-inputs", "label", "Label"),
        new("/neo-demo/ui/form-inputs", "textarea", "Textarea"),
        new("/neo-demo/ui/form-inputs", "numeric-input", "Numeric Input"),
        new("/neo-demo/ui/layout-controls", "button", "Button"),
        new("/neo-demo/ui/layout-controls", "button-group", "Button Group"),
        new("/neo-demo/ui/layout-controls", "split-button", "Split Button"),
        new("/neo-demo/ui/layout-controls", "tabs", "Tabs"),
        new("/neo-demo/ui/layout-controls", "accordion", "Accordion"),
        new("/neo-demo/ui/layout-controls", "collapsible", "Collapsible"),
        new("/neo-demo/ui/layout-tools", "separator", "Separator"),
        new("/neo-demo/ui/layout-tools", "resizable", "Resizable"),
        new("/neo-demo/ui/layout-tools", "sortable", "Sortable"),
        new("/neo-demo/ui/layout-tools", "theme-switcher", "Theme Switcher"),
        new("/neo-demo/ui/layout-tools", "localization", "Localization"),
        new("/neo-demo/ui/mobile", "app-bar", "AppBar"),
        new("/neo-demo/ui/mobile", "bottom-nav", "BottomNav"),
        new("/neo-demo/ui/mobile", "notification-badge", "Notification Badge"),
        new("/neo-demo/ui/mobile", "quantity-stepper", "Quantity Stepper"),
        new("/neo-demo/ui/mobile", "section-header", "Section Header"),
        new("/neo-demo/ui/navigation", "breadcrumb", "Breadcrumb"),
        new("/neo-demo/ui/navigation", "command", "Command"),
        new("/neo-demo/ui/navigation", "menubar", "Menubar"),
        new("/neo-demo/ui/navigation", "navigation-menu", "Navigation Menu"),
        new("/neo-demo/ui/navigation", "pagination", "Pagination"),
        new("/neo-demo/ui/navigation", "responsive-nav", "Responsive Nav"),
        new("/neo-demo/ui/navigation", "sidebar", "Sidebar"),
        new("/neo-demo/ui/overlays-floating", "dropdown-menu", "Dropdown Menu"),
        new("/neo-demo/ui/overlays-floating", "context-menu", "Context Menu"),
        new("/neo-demo/ui/overlays-floating", "popover", "Popover"),
        new("/neo-demo/ui/overlays-floating", "tooltip", "Tooltip"),
        new("/neo-demo/ui/overlays-floating", "hover-card", "Hover Card"),
        new("/neo-demo/ui/overlays-modal", "alert-dialog", "Alert Dialog"),
        new("/neo-demo/ui/overlays-modal", "dialog", "Dialog"),
        new("/neo-demo/ui/overlays-modal", "dialog-service", "Dialog Service"),
        new("/neo-demo/ui/overlays-modal", "drawer", "Drawer"),
        new("/neo-demo/ui/overlays-modal", "sheet", "Sheet"),
    ];
}
